import React, { Component } from 'react';
import classes from './App.css';
import CustomPerson from './Person/CustomPerson';

/*
  Working With CSS Modules
  Another way of scoping styles to your components or writing styles which only get applied to a specific
  component instead of the entire application because that is an important thing. Often you really want
  to make sure that your styles don't apply everywhere in your application but only to certain parts.

  That can be achieved with a novel concept as well CSS Modules. For CSS Modules to work, we need to
  tweak the configuration of our project a little bit. The underlying build configuration, the
  configuration which takes our code transforms it and bundles it together. To be precise, we need to
  tweak the configuration if we're using React scripts version 1 (check package.json file).

  If you are using React scripts version 2 or higher you have an alternative approach of enabling this
  feature which we will cover later. For version 1, you need to quit your development server and then
  run NPM eject in your project folder. What this will do is it will eject from this under the hood
  configuration where you don't really have access to the underlying web packed conflict file and so on
  and give access to the conflict files so that you can tweak how your code is bundled together and
  so on and there is something we will need to tweak there.

  npm run eject
  is the command you need to run on the terminal of VS Code. After running this command you will get a
  new config folder. In the config folder, you will find webpack.config.dev.js and webpack.config.prod.js
  these are the configuration files which are used by create-react-app to give you that development
  server and build you app and bundle it together.

  In dev file you will find line -> test: /\.css$/ and some other options. This is the part we need to
  tweak, below are the settings:
    importLoaders: 1,
    modules: true,
    localIdentName: '[name]__[local]__[hash:base64:5]'
  
  Understanding
  modules: true - enables to see us as modules feature which we're about to use and this will be used
  by that feature and
  '[name]__[local]__[hash:base64:5]' will be used by that feature to dynamically generate unique CSS
  as class names in the end.

  We also need to do the same in the prod file. What do we get by adding these configuration items?
  If we go to our App.js, we can import from our CSS file in a different way. We can import classes
  from. This is a different way of importing from the CSS file, which is now supported by the underlying
  built script because of our tweaks we just made. What this will do is, it will import all the classes
  we export here for example button.

  Explanation: The CSS Modules feature is a feature applied by some tool which is part of the build
  process. So if the process which takes our code and then compiles it, transforms it and bundles it
  together and this process simply detects this kind of import from a CSS file and understands that
  we don't just want to add the CSS as it is but instead it now looks into the CSS file transforms every
  class name here to a random unique one and returns us a map of these generated unique class names
  mapped to the class names we choose here as properties and is object which we import. So every class
  name we have in a CSS file is now a property of this imported object and the value for every property
  will be this randomly generated unique class name generated by this package. When you run and execute
  the project and inspect a button you will see the class it has, has some random hash value, it has
  the random name generated following our naming convention we set up in the webconfig. This is
  guaranteed to be unique only in this component and we can't clash with other components because only
  here I'm importing from App.css, if we use button class in other part of the app it will not clash
  with the styles here because it will not be applied as a button class to the element. But as this
  generated name, this is the idea behind CSS modules and therefore they allow us to move code into CSS
  files and still imported in a way that is scoped to this component.

  Question here is that how can we now implement such dynamic style changes, because we are not setting
  the styles in the JavaScript code anymore but in CSS files?
  We just have to add different CSS classes based on the styles we want. We can go to the App.css and
  then there we can add a new class Red by specifying a selector that means it will only be applied to
  the element which also has button class. In there, we can specify background-color to red.

  If you are using version 2 of React scripts then to use CSS modules you have to rename the CSS file
  like this:
  filename.modules.css
  And import them in the same way. Then we don't have to eject it.
*/

class App extends Component {
  state = {
    persons: [
      { id: 'abc', name: 'Max', age: 28 },
      { id: 'bcd', name: 'Manu', age: 29 },
      { id: 'cde', name: 'Stephanie', age: 26 }
    ],
    otherState: 'Some other value',
    showPersons: false
  }

  nameChangedHandler = (event, id) => {
    const personIndex = this.state.persons.findIndex(p => {
      return p.id === id
    })

    const person = {
      ...this.state.persons[personIndex]
    };

    person.name = event.target.value
    const persons = [...this.state.persons]
    persons[personIndex] = person
    this.setState({ persons: persons })
  }

  togglePersonsHandler = () => {
    const doesShow = this.state.showPersons
    this.setState({ showPersons: !doesShow })
  }

  deletePersonHandler = (personIndex) => {
    const persons = [...this.state.persons];
    persons.splice(personIndex, 1);
    this.setState({ persons: persons });
  }

  render() {
    let persons = null
    //let btnClass = [classes.button]
    let btnClass = ''
    
    /*
      Now btnClass is empty because we're not working with a default button class but any button inside
      of an App class.
    */

    if (this.state.showPersons) {
      persons = (
        <div>
          {
            this.state.persons.map((person, index) => {
              return <CustomPerson click={() => this.deletePersonHandler(index)}
                name={person.name} age={person.age} key={person.id}
                changed={(event) => this.nameChangedHandler(event, person.id)} />
            })
          }
        </div>
      )
      // btnClass.push(classes.Red) -> Code commented for other code.
      /*
          Button class is not an array.
      */
      btnClass = classes.Red
    }

    const assignedClasses = []
    if (this.state.persons.length <= 2) {
      assignedClasses.push(classes.red) // classes = ['red']
    }
    if (this.state.persons.length <= 1) {
      assignedClasses.push(classes.bold) // classes = ['red', 'bold']
    }

    return (
      <div className={classes.App}>
        <h1>Hi, I'm a React App</h1>

        <p className={assignedClasses.join(' ')}>This is really working!</p>
        <button className={classes.button} onClick={this.togglePersonsHandler}>Toggle Persons</button>
        {/*
          Because we have an array and I want to join all the classes that are in there together with
          a white space in between.

          Commenting this code to include other code option.
        */}
        <button /*className={btnClass.join(' ')}*/ className={btnClass}
          onClick={this.togglePersonsHandler}>Toggle Persons</button>

        {
          this.state.showPersons === true ?
            <div>
              {persons}
            </div>
            : null
        }
      </div>
    );
  }
}

export default App;
